version: "3.8"

services:
  pet_catalog:
    build: ./
    ports:
      - "3005:3000"
    volumes:
      - .:/rails
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16.2-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: pet_catalog
      POSTGRES_PASSWORD: pet_catalog

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis:/data
    ports:
      - "6385:6379"

volumes:
  postgresql:
  redis:
